collections:
  # BLOG ORIGINAL
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  # 🕵️ CASOS
  - name: "casos"
    label: "Casos"
    folder: "src/pages/casos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título del Caso", name: "title", widget: "string" }
      - { label: "Fecha del Caso", name: "fecha", widget: "datetime" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Personajes Involucrados", name: "personajes", widget: "list" }
      - { label: "Lugar del Crimen", name: "lugar", widget: "string" }
      - { label: "Resultado", name: "resultado", widget: "text" }
      - { label: "Imagen destacada", name: "imagen", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  # 👤 PERSONAJES
  - name: "personajes"
    label: "Personajes"
    folder: "src/pages/personajes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Alias", name: "alias", widget: "string", required: false }
      - { label: "Edad", name: "edad", widget: "string", required: false }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Afiliación", name: "afiliacion", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Biografía", name: "body", widget: "markdown" }

  # 📺 EPISODIOS
  - name: "episodios"
    label: "Episodios"
    folder: "src/pages/episodios"
    create: true
    slug: "episodio-{{slug}}"
    fields:
      - { label: "Número de Episodio", name: "numero", widget: "number" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de emisión", name: "fecha", widget: "datetime" }
      - { label: "Caso Asociado", name: "caso", widget: "string" }
      - { label: "Personajes Clave", name: "personajes", widget: "list" }
      - { label: "Imagen destacada", name: "imagen", widget: "image" }
      - { label: "Resumen", name: "body", widget: "markdown" }

  # 🧠 TEORÍAS
  - name: "teorias"
    label: "Teorías"
    folder: "src/pages/teorias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor o Usuario", name: "autor", widget: "string" }
      - { label: "Fecha", name: "fecha", widget: "datetime" }
      - { label: "Imagen", name: "imagen", widget: "image", required: false }
      - { label: "Teoría completa", name: "body", widget: "markdown" }

  # 🕶 ORGANIZACIONES
  - name: "organizaciones"
    label: "Organizaciones"
    folder: "src/pages/organizaciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Miembros conocidos", name: "miembros", widget: "list" }
      - { label: "Logo", name: "imagen", widget: "image", required: false }
      - { label: "Detalles", name: "body", widget: "markdown" }

  # 🗺 LUGARES
  - name: "lugares"
    label: "Lugares"
    folder: "src/pages/lugares"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Tipo de Lugar", name: "tipo", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imagen", name: "imagen", widget: "image", required: false }
      - { label: "Información detallada", name: "body", widget: "markdown" }
